### ISSUE TITLE
Handle error null in iam_user_not_allowed_to_create_security_group & iam_user_not_allowed_to_register_application

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-mod-azure-compliance#216]
**Describe the bug**
Used in CIS controls 

```sql
  select
      a.id as resource,
      case
        when a.default_user_role_permissions ->> 'allowedToCreateSecurityGroups' = 'false' then 'ok'
        else 'alarm'
      end as status,
      case
        when a.default_user_role_permissions ->> 'allowedToCreateSecurityGroups' = 'false' then a.display_name || ' does not allow user to create security groups.'
        else a.display_name || ' allows user to create security groups.'
      end as reason,
      t.tenant_id
    from
      azure_tenant as t,
      azuread_authorization_policy as a;
```
```
Error: null (SQLSTATE HV000)

+----------+--------+--------+-----------+
| resource | status | reason | tenant_id |
+----------+--------+--------+-----------+
+----------+--------+--------+-----------+
```
Same result for 
`iam_user_not_allowed_to_register_application`

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

**Comment by khushboo9024** [comment]
@rajlearner17 Thanks for raising the issue. 
The above query functions smoothly with a premium Azure AD, but it encounters errors when used with a free Azure AD. 

Resolving this issue requires addressing it at the plugin level since the error originates from the table itself.

<img width="1440" alt="image" src="https://github.com/turbot/steampipe-mod-azure-compliance/assets/46913995/baf55618-27b2-4003-b758-b153625bbdd0">

**Comment by misraved** [comment]
@khushboo9024 could you please raise an issue in the plugin to handle this error?
